-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object exposing (Color(..), Kayoinoba(..), KayoinobaAttributes(..), Location(..), Map(..), ModelKayoinobaConnection(..), ModelMapConnection(..), ModelPlaceConnection(..), Place(..))


type Color
    = Color


type Kayoinoba
    = Kayoinoba


type KayoinobaAttributes
    = KayoinobaAttributes


type Location
    = Location


type Map
    = Map


type ModelKayoinobaConnection
    = ModelKayoinobaConnection


type ModelMapConnection
    = ModelMapConnection


type ModelPlaceConnection
    = ModelPlaceConnection


type Place
    = Place
