-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Color exposing (alpha, blue, green, red)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


red : SelectionSet Int Api.Object.Color
red =
    Object.selectionForField "Int" "red" [] Decode.int


green : SelectionSet Int Api.Object.Color
green =
    Object.selectionForField "Int" "green" [] Decode.int


blue : SelectionSet Int Api.Object.Color
blue =
    Object.selectionForField "Int" "blue" [] Decode.int


alpha : SelectionSet Float Api.Object.Color
alpha =
    Object.selectionForField "Float" "alpha" [] Decode.float
