-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.KayoinobaAttributes exposing (free, insyokuari, noutore, ongaku, taisou, undou)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


taisou : SelectionSet Bool Api.Object.KayoinobaAttributes
taisou =
    Object.selectionForField "Bool" "taisou" [] Decode.bool


noutore : SelectionSet Bool Api.Object.KayoinobaAttributes
noutore =
    Object.selectionForField "Bool" "noutore" [] Decode.bool


ongaku : SelectionSet Bool Api.Object.KayoinobaAttributes
ongaku =
    Object.selectionForField "Bool" "ongaku" [] Decode.bool


insyokuari : SelectionSet Bool Api.Object.KayoinobaAttributes
insyokuari =
    Object.selectionForField "Bool" "insyokuari" [] Decode.bool


undou : SelectionSet Bool Api.Object.KayoinobaAttributes
undou =
    Object.selectionForField "Bool" "undou" [] Decode.bool


free : SelectionSet Bool Api.Object.KayoinobaAttributes
free =
    Object.selectionForField "Bool" "free" [] Decode.bool
