-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Kayoinoba exposing (attributes, contact, createdAt, id, kayoinobaPlaceId, mapIdForSearch, name, place, price, summary, target, updatedAt, webSite, yomigana)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet Api.ScalarCodecs.Id Api.Object.Kayoinoba
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecId |> .decoder)


name : SelectionSet String Api.Object.Kayoinoba
name =
    Object.selectionForField "String" "name" [] Decode.string


place :
    SelectionSet decodesTo Api.Object.Place
    -> SelectionSet decodesTo Api.Object.Kayoinoba
place object____ =
    Object.selectionForCompositeField "Place" [] object____ Basics.identity


yomigana : SelectionSet String Api.Object.Kayoinoba
yomigana =
    Object.selectionForField "String" "yomigana" [] Decode.string


summary : SelectionSet String Api.Object.Kayoinoba
summary =
    Object.selectionForField "String" "summary" [] Decode.string


price : SelectionSet (Maybe Int) Api.Object.Kayoinoba
price =
    Object.selectionForField "(Maybe Int)" "price" [] (Decode.int |> Decode.nullable)


target : SelectionSet String Api.Object.Kayoinoba
target =
    Object.selectionForField "String" "target" [] Decode.string


contact : SelectionSet String Api.Object.Kayoinoba
contact =
    Object.selectionForField "String" "contact" [] Decode.string


webSite : SelectionSet (Maybe Api.ScalarCodecs.Awsurl) Api.Object.Kayoinoba
webSite =
    Object.selectionForField "(Maybe ScalarCodecs.Awsurl)" "webSite" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecAwsurl |> .decoder |> Decode.nullable)


attributes :
    SelectionSet decodesTo Api.Object.KayoinobaAttributes
    -> SelectionSet decodesTo Api.Object.Kayoinoba
attributes object____ =
    Object.selectionForCompositeField "attributes" [] object____ Basics.identity


mapIdForSearch : SelectionSet Api.ScalarCodecs.Id Api.Object.Kayoinoba
mapIdForSearch =
    Object.selectionForField "ScalarCodecs.Id" "mapIdForSearch" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecId |> .decoder)


createdAt : SelectionSet Api.ScalarCodecs.AWSDateTime Api.Object.Kayoinoba
createdAt =
    Object.selectionForField "ScalarCodecs.AWSDateTime" "createdAt" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecAWSDateTime |> .decoder)


updatedAt : SelectionSet Api.ScalarCodecs.AWSDateTime Api.Object.Kayoinoba
updatedAt =
    Object.selectionForField "ScalarCodecs.AWSDateTime" "updatedAt" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecAWSDateTime |> .decoder)


kayoinobaPlaceId : SelectionSet Api.ScalarCodecs.Id Api.Object.Kayoinoba
kayoinobaPlaceId =
    Object.selectionForField "ScalarCodecs.Id" "kayoinobaPlaceId" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecId |> .decoder)
