-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Map exposing (category1Name, category2Name, category3Name, centerLocation, createdAt, id, name, themeColor, title, topInformation, updatedAt, zoom)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet Api.ScalarCodecs.Id Api.Object.Map
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecId |> .decoder)


name : SelectionSet String Api.Object.Map
name =
    Object.selectionForField "String" "name" [] Decode.string


title : SelectionSet String Api.Object.Map
title =
    Object.selectionForField "String" "title" [] Decode.string


topInformation : SelectionSet String Api.Object.Map
topInformation =
    Object.selectionForField "String" "topInformation" [] Decode.string


zoom : SelectionSet Int Api.Object.Map
zoom =
    Object.selectionForField "Int" "zoom" [] Decode.int


centerLocation :
    SelectionSet decodesTo Api.Object.Location
    -> SelectionSet decodesTo Api.Object.Map
centerLocation object____ =
    Object.selectionForCompositeField "centerLocation" [] object____ Basics.identity


category1Name : SelectionSet String Api.Object.Map
category1Name =
    Object.selectionForField "String" "category1Name" [] Decode.string


category2Name : SelectionSet String Api.Object.Map
category2Name =
    Object.selectionForField "String" "category2Name" [] Decode.string


category3Name : SelectionSet String Api.Object.Map
category3Name =
    Object.selectionForField "String" "category3Name" [] Decode.string


themeColor :
    SelectionSet decodesTo Api.Object.Color
    -> SelectionSet decodesTo Api.Object.Map
themeColor object____ =
    Object.selectionForCompositeField "themeColor" [] object____ Basics.identity


createdAt : SelectionSet Api.ScalarCodecs.AWSDateTime Api.Object.Map
createdAt =
    Object.selectionForField "ScalarCodecs.AWSDateTime" "createdAt" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecAWSDateTime |> .decoder)


updatedAt : SelectionSet Api.ScalarCodecs.AWSDateTime Api.Object.Map
updatedAt =
    Object.selectionForField "ScalarCodecs.AWSDateTime" "updatedAt" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecAWSDateTime |> .decoder)
