-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.ModelPlaceConnection exposing (items, nextToken)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


items :
    SelectionSet decodesTo Api.Object.Place
    -> SelectionSet (List (Maybe decodesTo)) Api.Object.ModelPlaceConnection
items object____ =
    Object.selectionForCompositeField "items" [] object____ (Basics.identity >> Decode.nullable >> Decode.list)


nextToken : SelectionSet (Maybe String) Api.Object.ModelPlaceConnection
nextToken =
    Object.selectionForField "(Maybe String)" "nextToken" [] (Decode.string |> Decode.nullable)
