-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Place exposing (address, category, contact, createdAt, hasImage, id, location, map, name, placeMapId, updatedAt)

import Api.Enum.PlaceCategory
import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet Api.ScalarCodecs.Id Api.Object.Place
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecId |> .decoder)


map :
    SelectionSet decodesTo Api.Object.Map
    -> SelectionSet decodesTo Api.Object.Place
map object____ =
    Object.selectionForCompositeField "Map" [] object____ Basics.identity


name : SelectionSet String Api.Object.Place
name =
    Object.selectionForField "String" "name" [] Decode.string


address : SelectionSet String Api.Object.Place
address =
    Object.selectionForField "String" "address" [] Decode.string


category : SelectionSet Api.Enum.PlaceCategory.PlaceCategory Api.Object.Place
category =
    Object.selectionForField "Enum.PlaceCategory.PlaceCategory" "category" [] Api.Enum.PlaceCategory.decoder


contact : SelectionSet String Api.Object.Place
contact =
    Object.selectionForField "String" "contact" [] Decode.string


location :
    SelectionSet decodesTo Api.Object.Location
    -> SelectionSet decodesTo Api.Object.Place
location object____ =
    Object.selectionForCompositeField "location" [] object____ Basics.identity


hasImage : SelectionSet Bool Api.Object.Place
hasImage =
    Object.selectionForField "Bool" "hasImage" [] Decode.bool


createdAt : SelectionSet Api.ScalarCodecs.AWSDateTime Api.Object.Place
createdAt =
    Object.selectionForField "ScalarCodecs.AWSDateTime" "createdAt" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecAWSDateTime |> .decoder)


updatedAt : SelectionSet Api.ScalarCodecs.AWSDateTime Api.Object.Place
updatedAt =
    Object.selectionForField "ScalarCodecs.AWSDateTime" "updatedAt" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecAWSDateTime |> .decoder)


placeMapId : SelectionSet Api.ScalarCodecs.Id Api.Object.Place
placeMapId =
    Object.selectionForField "ScalarCodecs.Id" "placeMapId" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecId |> .decoder)
